---@class RoomConfigRoom
---@field Difficulty Difficulty @const
---@field Doors integer @const
---@field Height integer @const
---@field InitialWeight number @const
---@field Mode integer @const
---@field Name string @const
---@field Shape RoomShape @const
---@field OriginalVariant integer @const | Not officially documented but functional
---@field SpawnCount integer @const
---@field Spawns CppList_RoomConfigSpawn @const
---@field StageID integer @const
---@field Subtype integer @const
---@field Type RoomType @const
---@field Variant integer @const
---@field Weight number @const
---@field Width integer @const
local RoomConfigRoom = {}
