---@class ProjectileParams
---@field Acceleration number
---@field BulletFlags integer
---@field ChangeFlags integer
---@field ChangeTimeout integer
---@field ChangeVelocity number
---@field CircleAngle number
---@field Color Color
---@field CurvingStrength number
---@field Damage number **Warning:** Enemies that are champions will cap the damage at 2.
---@field DepthOffset number
---@field DotProductLimit number
---@field FallingAccelModifier number
---@field FallingSpeedModifier number
---@field FireDirectionLimit Vector
---@field GridCollision boolean
---@field HeightModifier number
---@field HomingStrength number
---@field PositionOffset Vector
---@field Scale number
---@field Spread number
---@field TargetPosition Vector
---@field Variant integer
---@field VelocityMulti number
---@field WiggleFrameOffset integer
