name: Prepare Addon and Sync Branches

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run prepare_addon script
        run: |
          python scripts/prepare_addon.py
      
      - name: Upload artifact for publish job 
        uses: actions/upload-artifact@v4
        with:
          name: addon-artifact
          path: ${{ github.workspace }}/merge/addon

  publish:
    needs: prepare
    runs-on: ubuntu-latest

    env:
      ARTIFACT_DIR: ${{ github.workspace }}/addon
    strategy:
      matrix:
        target:
          - name: vanilla
            branch: addon/vanilla
            source: vanilla
          - name: repentogon
            branch: addon/repentogon
            source: repentogon
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: addon-artifact
          path: ${{env.ARTIFACT_DIR}}

      # - name: Debug artifact
      #   run: ls -lR ${{env.ARTIFACT_DIR}}
      
      - name: Publish addon versions
        env:
          TARGET_BRANCH: ${{ matrix.target.branch }}
          SOURCE_DIR: ${{ env.ARTIFACT_DIR }}/${{ matrix.target.source }}
        run: |
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          # avoid warning
          git config --global init.defaultBranch main
          TEMP_DIR=$(mktemp -d)

          cd "$TEMP_DIR"
          git init
          git remote add origin "${{ github.repositoryUrl }}"
          git fetch --depth=1 origin "$TARGET_BRANCH" || true

          if git show-ref --verify --quiet "refs/remotes/origin/$TARGET_BRANCH"; then
            git checkout "$TARGET_BRANCH"
          else
            git checkout --orphan "$TARGET_BRANCH"
          fi

          rsync -a --delete --exclude='.git' "$SOURCE_DIR/" ./

          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "🚀 Update ${matrix.target.name} addon"

            git push --force --set-upstream origin "$TARGET_BRANCH"
          else
            echo "No changes in $TARGET_BRANCH content to commit."
          fi
